# Generated by Django 2.2.16 on 2021-11-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
