# Generated by Django 2.2.16 on 2021-11-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'user'), ('MD', 'moderator'), ('AD', 'admin')], default='US', max_length=200, verbose_name='Пользовательские роли'),
        ),
    ]
